spring:
  application:
    name: dao-cloud-example-gateway
server:
  port: 19997
  servlet:
    context-path: /${spring.application.name}

dao-cloud:
#  如果没有此项配置的话,默认为单机的127.0.0.1去连接.
#   center:
#     ip: 192.168.31.254
#  设置为网关中心
  gateway:
    enable: true
    #版本(默认: 0)
    #version: 0
    #路由策略   RANDOM(默认) HASH ROUND
    #loadBalance: RANDOM

log.home: /data/dao-cloud-logs/${spring.application.name}