spring:
  application:
    name: dao-cloud-example-provider
server:
  port: 19999
  servlet:
    context-path: /${spring.application.name}

dao-cloud:
  enable: true
  server:
    proxy: demo
    corePoolSize: 3
    maxPoolSize: 40
  center:
    # 如果没有此项配置的话,默认为单机的127.0.0.1去连接.
#    ip: 192.168.31.254

log.home: /data/dao-cloud-logs/${spring.application.name}