spring:
  application:
    name: dao-cloud-example-provider
server:
  port: 19999
  servlet:
    context-path: /${spring.application.name}

dao-cloud:
  enable: true
  proxy: demo
  corePoolSize: 3
  maxPoolSize: 40

log.home: /data/dao-cloud-logs/${spring.application.name}