spring:
  application:
    name: web
log.home: /data/dao-cloud-logs/${spring.application.name}
server:
  port: 5555
#  servlet:
#    context-path: /dao-cloud
dao-cloud:
  center:
    dashboard: true
  config:
    persistence: file-system # file-system(本地文件)、mysql
    prefix: /data/dao-cloud/config
#    mysql:
#      url: 192.168.1.14
#      username: root
#      password: JunMo123