spring:
  application:
    name: web
log.home: /data/dao-cloud-logs/${spring.application.name}
server:
  port: 5555
#  servlet:
#    context-path: /dao-cloud
dao-cloud:
  center:
    dashboard: true
    ############################ 集群方式 ############################
    cluster:
      ip: 127.0.0.1
    ############################ 集群方式 ############################
    ############################ 配置中心 ############################
    config:
      persistence: file-system # file-system(本地文件)、mysql
      # 配置文件存储地址
      file-system-setting:
        pathPrefix: /data/dao-cloud/config
      # 配置文件存放mysql的地址
      # mysql-setting:
      # url: 192.168.31.23
      # port: 3306
      # username: root
      # password: JunMo123
    ############################ 配置中心 ############################