spring:
  application:
    name: web
log.home: /data/dao-cloud/${spring.application.name}
server:
  port: 5555
  servlet:
    context-path: /dao-cloud
dao-cloud:
  # jdk or json or protobuf
  serializer: jdk
  center:
    dashboard: true