spring:
  application:
    name: web
log.home: /data/dao-cloud-logs/${spring.application.name}
server:
  port: 5555
#  servlet:
#    context-path: /dao-cloud
dao-cloud:
  center:
    admin-web:
      # 是否要开启可视化管理页面
      dashboard: true
      # 设置登陆账号密码
      username: admin
      password: 123456
    ############################ 集群方式 ############################
    # 配置第一个节点center必须是空，后续加入cluster中必须填写值。值可以是任意一个存活节点的ip地址
#    cluster:
#      ip: 192.168.31.254
    ############################ 集群方式 ############################
    ############################ 配置中心 ############################
    # 存储方式：file-system(本地文件)、mysql
    storage:
      way: file-system
      # 配置文件存储地址
      file-system-setting:
        path-prefix: /data/dao-cloud/config
      # 配置文件存放mysql的地址
      # mysql-setting:
      # url: 192.168.31.23
      # port: 3306
      # username: root
      # password: JunMo123
    ############################ 配置中心 ############################