spring:
  application:
    name: dao-cloud-example-consumer
server:
  port: 19998
  servlet:
    context-path: /${spring.application.name}

dao-cloud:
  server:
    enable: true
    proxy: demo2
    corePoolSize: 3
    maxPoolSize: 40

log.home: /data/dao-cloud-logs/${spring.application.name}